from pathlib import Path
import hashlib,json,shutil,subprocess,xml.etree.ElementTree as ET
ROOT=Path('/workspace/scratch/745337b67ff9')
SRC=ROOT/'qualification-launcher-consumer-400'
OUT=ROOT/'qualification-launcher-consumer-validation'
PATHS=['scripts/native_slo_launcher_offers.py','scripts/native_slo_launcher_consumer.py','scripts/native_slo_lifetime_cpu.py','scripts/native_slo_launcher_resources.py','scripts/native_slo_resources.py','tests/test_launcher_group_resources.py','tests/test_launcher_offer_ledger.py','tests/test_launcher_measurement_consumer.py']
def record(path,body):
 return {'path':path,'bytes':len(body),'sha256':hashlib.sha256(body).hexdigest(),'git_blob':hashlib.sha1(b'blob '+str(len(body)).encode()+b'\0'+body).hexdigest()}
def write(name,value):
 (OUT/name).write_text(json.dumps(value,indent=2,sort_keys=True)+'\n')
files=[]
for name in PATHS:
 body=(SRC/name).read_bytes();target=OUT/'source'/name;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(body);files.append(record(name,body))
xml=ET.parse(OUT/'controls-v3.xml');cases=list(xml.iter('testcase'))
assert len(cases)==179 and sum(c.find('skipped') is not None for c in cases)==1
assert not list(xml.iter('failure')) and not list(xml.iter('error'))
checks=json.loads((OUT/'types-v3.json').read_text());assert checks['summary']['errorCount']==0
providers=[]
for name in ['scripts/native_slo_priority_launchers.py','scripts/native_slo_qualification.py','scripts/native_slo_acceptance.py','scripts/native_slo_contract.py','scripts/native_qualification_interpreter.py','scripts/native_qualification_process.py']:
 providers.append(record(name,(SRC/name).read_bytes()))
inputs=[]
for name in ['normal-a5fd-posix/10609894892/raw/native-installed-slo.json','normal400-posix/linux-terminal/10611308317/raw/native-installed-slo.json','normalb222-posix/linux-terminal/10613212321/raw/native-installed-slo.json','qualification-recovered/phase-installed-35517987547/VERIFIED-RESULT.json']:
 inputs.append(record(name,(ROOT/name).read_bytes()))
old=json.loads((ROOT/'qualification-recovered/daemon-lazy-next-plan/OPTIMIZED-PYTHON-MEASUREMENT-PLAN.json').read_text())
tasks=json.loads((ROOT/'root-checkpoint/current400-progress-docs/task-status-overlay.json').read_text())['tasks']
selected=[{key:t[key] for key in ('id','title','original_acceptance','original_dependencies')} for t in tasks if t['number'] in [7,10,11,12,25,85,121,136,137,138,140,144]]
artifacts=[]
for label,directory,source,tree in [('baseline','normal-a5fd-posix/10609894892','a5fdde302aba2a06265c2e6e934b6ac9b76750df','ee96f00e4e97fe38ab9e6782b35f92ab0aebb5e9'),('candidate','normalb222-posix/linux-terminal/10613212321','b222318cca2811ac7ae90c7364e2ec6d0a10651f','ef0c0b8abb8144ed010b4c23c05a2dc70f20c354')]:
 d=ROOT/directory;v=json.loads((d/'verification.json').read_text());runtime=json.loads((d/'raw/native-artifact-evidence.json').read_text())
 artifacts.append({'arm':label,'product_source':source,'product_tree':tree,'archive':{key:v[key] for key in ('artifact_id','archive_bytes','archive_sha256')},'native_wheel':next(m for m in v['members'] if 'manylinux' in m['path']),'original_runtime_evidence':runtime,'prerequisite':'Original admission reused as identity evidence; exact install/RECORD/owned-interpreter/source-before-and-after is still required for each new arm. No old sample is reused.'})
plan={
 'schema':'pr2974.linux-priority-launcher-measurement-plan.v2',
 'status':'source_and_budget_proposal_not_dispatch_ready',
 'created_utc':'2026-09-20T21:13:50Z',
 'execution_performed':False,
 'supersedes_only_proposal':{'prior_plan_git_blob':'902e47538879fc0812e26d96b3b0e593f75fb964','prior_packet_tree':'c30f7d3ed01463e945415e80259a65be77131527','retained':True,'changes':['Linux first after actual protected lifetime CPU proof.','Six independent paired jobs instead of all six pairs in one host job; each pair uses the same host.','Actual a5fd baseline versus b222 combined current candidate; pure lazy-only tree50e5 remains unbuilt/source-only.','Add actual offered-call ledger and protected live-member sampling/strict measurement consumer.']},
 'question':'Does the selected current Python implementation plus declared concurrent correctness changes improve registered priority launchers versus the authentic pre-lazy a5fd artifact while preserving outcomes and fully observed interval resources?',
 'artifact_selection':artifacts,
 'causal_limit':'Candidate b222 contains the seven-export lazy initializer, six encrypted-post Rust changes and test/Gitleaks follow-up. Original priority payloads are inline, but no one-file causal attribution is inferred. Both native digests remain explicit; pure-lazy causal comparison would require its own authentic artifact and separate selection.',
 'population':old['proposed_first_timed_scope'],
 'hardware_admission':{'platform':'linux-x64','jobs':6,'same_host_within_each_pair':True,'same_host_across_pairs':False,'matched_hardware_class_required':True,'hardware_class_fields':['architecture','CPU model','online core count','RAM class','OS release','kernel release','runner image','power/governor mode','interpreter bytes/version'],'dynamic_covariates':['background load before/after each arm','actual RAM','runner job/boot identity'],'unknown_or_mismatched_required_fields':'No dependent qualification claim; all original offered rows retained. No automatic replacement host or discarded failed block. The operational driver must admit required facts before any product offer.'},
 'budget':{'source_records':inputs,'observed_planning_inputs':{'a5fd_linux_ClaudePost_smoke_count':2,'a5fd_linux_ClaudePost_max_ms':213.134,'b222_linux_ClaudePost_smoke_count':2,'b222_linux_ClaudePost_max_ms':153.108,'older_instrumented_ARM_four_route_max_serial_ms':303.722,'older_instrumented_ARM_max_c16_wave_ms':1756.577},'use_limit':'Historical smoke and instrumented different-platform values are planning covariates only. They are neither representative promises nor pooled new measurements. No clean regression/gain inference.', 'serial_preflight_cold_calls_per_arm':6744,'c16_waves_per_arm':420,'planning_seconds_per_arm_at_larger_retained_covariates':2786.063508,'planning_minutes_per_pair':92.8687836,'worker_wall_minutes_per_arm':80,'pair_work_wall_minutes':165,'host_job_wall_minutes':190,'post_work_cleanup_export_reserve_minutes':25,'maximum_parallel_jobs':2,'maximum_successful_original_offers':161568,'maximum_inflight_per_host':16,'analysis_consumer_address_space_bytes':536870912,'benchmark_worker_address_space_limit':None,'memory_budget_scope':'No new inherited RLIMIT_AS or memory.max is imposed on product children. Bounded ledger/sample state and8MiB packet cap constrain observer memory; actual declared host RAM/available memory is required before admission and all process resources remain observed.','packet_per_arm_bytes':8388608,'live_process_bound':4096,'sample_period_seconds':0.1,'no_silent_budget_reset':True,'failure_policy':'Original per-launch10s, c16 collection30s and payload4000ms remain unchanged. Whole-arm wall expiry records partial offered rows and fails the block; it does not retry a request, replace the arm or omit its failure. Whole-campaign acceptance requires all twelve original arms.', 'hosted_job_limit_reference':'https://docs.github.com/en/enterprise-cloud%40latest/actions/reference/limits','hosted_limit_hours_verified':6,'operational_caveat':'Do not reuse the finite45s parent wrapper. A separately reviewed bounded controller must drain/report the actual arm, terminate only its owned group on outer failure, and preserve cleanup failures. No root product imports; worker placement/drop/admission precedes every fixture child.'},
 'resource_semantics':{'lifetime_cpu':'Protected cgroup kernel counters include all members charged during the whole original producer bracket, including exited/reparented descendants. They include worker, ledger, collector and original receipt waits; exclude privileged parent-controller CPU, outside services and work after the final snapshot. No subtraction.','denominator':'Every actually offered call in the fixed mix, including8 benign/block preflights per block. Completed count must equal offered count and declared coordinates before CPU/request can contribute to comparison. This is mixed-population interval CPU per attempt, not per-route warm-only CPU.','live_private_memory':'Protected cgroup.procs, pinned group and unchanged no-subgroup invariant. PID/create-time inventory before/after each sample includes reparented members. USS is summed only for a successful sampled live inventory. It is sampled private memory, not RSS, instantaneous peak or coverage of short-lived memory peaks between samples.','minima':'At least30 successful samples per required private/RSS/process/thread/descriptor metric; sticky missing/denied metrics and unavailable samples fail their scope. Lifetime CPU replaces the incomplete polled CPU source only. First failed retry followed by successful inventory remains the original sampler behavior; no claim of zero transient churn.','next_required_real_controls':['Actual private protected group: live child plus live reparented grandchild retained in group, each original process identity queried; verify summed USS/RSS and explicit sampled scope.','Actual fixed finite allocation/release plus singleton end witness and cleanup; no orphan waitpid claim.','Lost membership/closed fd, PID reuse, denied USS, partial callback/producer tail and no-subgroup refusal remain explicit controls.'],'currently_proved':'Actual finite-five lifetime CPU packet a4de0f2b and independent peer f31c812a. New protected live-member source has local real sibling reads plus modeled kernel identity/race controls; hosted private-group positive not yet executed.'},
 'consumer':'New strict reader admits full original offered coordinate roster, returned timings against raw producer series, exact identities before/after, host pair order and nonoverlapping same-clock intervals. Recomputes confidence summaries and original paired ratio intervals; never trusts an aggregate pass flag.',
 'thresholds':old['unchanged_acceptance'],
 'relative_predicate_exact':'independent AND ((ANY four serial-p95 paired upper CI <=0.70 AND whole-interval CPU upper CI <=1.05) OR (ALL four serial-p95 upper CIs <=1.05 AND CPU upper CI <=0.70)). This exact original predicate is separately reported; selected-tranche acceptance also requires all original absolute per-block upper-CI ceilings, route minima and required interval resource availability.',
 'next_task_mapping':selected,
 'task_scope':'This prepares the priority closed-loop measurement portions of010/011/012 and a bounded137 tranche.007 own measurement boundary is already separately assessed. No saturation/offered-rate/other modes/platforms/recovery/distribution/final-review completion is inferred; original dependencies are unchanged.',
 'history_preserved':old['history_preserved']+['Stopped E/F populations remain stopped and are not reoffered by this plan.','Old176/88/24 and normal smoke data are never pooled with the new campaign.','Both earlier finite CPU admission failures remain failures; unavailable historical cpu.stat is not reconstructed.'],
 'gates_before_any_campaign':['Final source and strict-reader independent peer.','Actual hosted protected live-member/private-memory finite controls and data peer.','Exact current selected artifact/source/build/RECORD/member/runtime/corpus/provider binding, default features, owned interpreter integrity proof and no preexisting profiler/sitecustomize.','Concrete two-arm host controller/workflow operational peer with required metric/environment preadmission and original producer exactly once per arm.','Full original task dependencies and missing qualification scopes remain visible; source tests do not imply installed performance success.'],
 'qualification_complete':False,
}
plan['population']=dict(plan['population'])
plan['population']['platform']='Linux x64 first; no transfer to other required platforms'
plan['population']['arms']=['authentic_a5fd_eager_manager','authentic_b222_current_combined_candidate']
plan['population']['scheduling']='Six independent paired jobs; each pair runs sequentially on its own admitted host. Existing paired_order alternates baseline/candidate by pair index. Same matched hardware class, no new pacing/warmup/retry; original internal route order and c16 barriers unchanged.'
plan['population']['scope']='Qualification-sized priority-launcher tranche proposal only; no original workload executed by this preparation.'
write('PLAN-v2.json',plan)
manifest={'schema':'pr2974.launcher-consumer-source-preparation.v1','source_base':'f0dba4e5be79912089e50c9ed7146f75ed8668a2','source_base_tree':'8d3de6a1ae2f17beff142473ddf6dfcfef89a0e1','local_checkout_head':'4001185e4f39cad51fd5eab314bf02b86b8a1674','inherited_diagnostic_source':'The eight frozen f0 overlays are retained; this tuple changes three of those/ordinary resource paths and adds two consumer/ledger scripts plus three control modules. No src product path changes.','files':files,'unchanged_providers':providers,'validation':{'cases':179,'passed':178,'skipped':1,'skip_scope':'existing explicit real-protected-cgroup environment-only control; no claim it ran locally','types':checks['summary'],'format_lint':'zero on all eight selected paths','prior_failures_retained':['initial.xml:115pass/1fail/1skip due passing new optional None keyword into existing controlled sampler signature; default forwarding restored.','types-initial.json:14 finite local checker errors; subsequent typing-only/narrow guards retained.']},'scope':'Untimed source/data/finite owned-child controls only; no installed launcher performance or hosted new private-group execution.','plan':record('PLAN-v2.json',(OUT/'PLAN-v2.json').read_bytes())}
write('SOURCE-MANIFEST.json',manifest)
print(json.dumps({'files':len(files),'cases':len(cases),'plan':record('PLAN-v2.json',(OUT/'PLAN-v2.json').read_bytes()),'manifest':record('SOURCE-MANIFEST.json',(OUT/'SOURCE-MANIFEST.json').read_bytes())},indent=2))
