from __future__ import annotations

import hashlib
import importlib.metadata
import json
import zipfile
from pathlib import Path
from types import SimpleNamespace
from typing import cast

import pytest

from scripts.ci.launcher_campaign_identity import digest, unique_pairs, wheel_members


def distribution(root: Path) -> importlib.metadata.Distribution:
    return cast(importlib.metadata.Distribution, cast(object, SimpleNamespace(locate_file=lambda name: root / name)))


def fixture(tmp_path: Path) -> tuple[Path, Path]:
    wheel = tmp_path / "source.whl"
    root = tmp_path / "installed"
    files = {
        "codex_plugin_scanner/__init__.py": b"value = 1\n",
        "codex_plugin_scanner/empty.py": b"",
        "hol_guard.dist-info/METADATA": b"Name: hol-guard\n",
        "hol_guard.dist-info/RECORD": b"original wheel RECORD\n",
    }
    with zipfile.ZipFile(wheel, "w") as archive:
        for name, body in files.items():
            archive.writestr(name, body)
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(body)
    return wheel, root


def test_original_members_include_empty_files_and_exclude_generated_cache_census(tmp_path: Path) -> None:
    wheel, root = fixture(tmp_path)
    cache = root / "codex_plugin_scanner/__pycache__/generated.pyc"
    cache.parent.mkdir()
    cache.write_bytes(b"generated bytecode is outside original-member scope")
    (root / "hol_guard.dist-info/RECORD").write_bytes(b"installed RECORD verified by separate original verifier")
    assert wheel_members(distribution(root), wheel) == 3
    assert digest(root / "codex_plugin_scanner/empty.py") == {"bytes": 0, "sha256": hashlib.sha256(b"").hexdigest()}


@pytest.mark.parametrize("kind", ["tamper", "missing", "symlink", "escaping_parent"])
def test_real_member_identity_refusals(tmp_path: Path, kind: str) -> None:
    wheel, root = fixture(tmp_path)
    original = root / "codex_plugin_scanner/__init__.py"
    if kind == "tamper":
        original.write_bytes(b"value = 2\n")
    elif kind == "missing":
        original.unlink()
    elif kind == "symlink":
        target = tmp_path / "target"
        target.write_bytes(original.read_bytes())
        original.unlink()
        original.symlink_to(target)
    else:
        moved = tmp_path / "outside"
        original.parent.rename(moved)
        original.parent.symlink_to(moved, target_is_directory=True)
    with pytest.raises((ValueError, OSError)):
        wheel_members(distribution(root), wheel)


@pytest.mark.parametrize("name", ["../escape", "/absolute"])
def test_unsafe_original_wheel_name_refuses_before_target_lookup(tmp_path: Path, name: str) -> None:
    wheel, root = fixture(tmp_path)
    with zipfile.ZipFile(wheel, "a") as archive:
        archive.writestr(name, b"unsafe")
    with pytest.raises(ValueError, match="path"):
        wheel_members(distribution(root), wheel)


def test_duplicate_original_wheel_names_refused(tmp_path: Path) -> None:
    wheel, root = fixture(tmp_path)
    with zipfile.ZipFile(wheel, "a") as archive, pytest.warns(UserWarning):
        archive.writestr("codex_plugin_scanner/empty.py", b"")
    with pytest.raises(ValueError, match="duplicate"):
        wheel_members(distribution(root), wheel)


def test_record_origin_json_duplicates_are_never_last_wins() -> None:
    with pytest.raises(ValueError, match="duplicate"):
        json.loads('{"url":"one","url":"two"}', object_pairs_hook=unique_pairs)


@pytest.fixture
def installed_subject(tmp_path: Path, monkeypatch):
    """Actual identity orchestration with explicit modeled installed APIs.

    Real temporary wheel/member/provider/interpreter bytes are read; native
    capability and installer APIs are modeled, never a native execution.
    """
    import sys
    from typing import Any

    from scripts.ci import launcher_campaign_identity as module

    prefix = tmp_path / "venv"
    python = prefix / "bin/python"
    python.parent.mkdir(parents=True)
    python.write_bytes(b"owned-interpreter-image")
    python.chmod(0o755)
    wheel, installation = fixture(prefix)
    runtime = installation / "runtime"
    runtime.write_bytes(b"modeled-native-image")
    providers = tmp_path / "providers"
    rows = []
    for name, body in (
        ("scripts/native_slo_priority_launchers.py", b"original-producer"),
        ("tests/fixtures/guard-native-qualification/corpus.v1.json", b"original-corpus"),
    ):
        path = providers / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
        rows.append({"path": name, **digest(path)})
    observed: list[str] = []
    state: dict[str, Any] = {"record": "e" * 64, "failure": None, "environment": [], "package": "d" * 64}

    def note(stage: str, result: Any = None) -> Any:
        observed.append(stage)
        if state["failure"] == stage:
            raise RuntimeError(stage)
        return result

    distribution_api = SimpleNamespace(
        version="3.0.1",
        locate_file=lambda name: installation / name,
        read_text=lambda _name: json.dumps({"url": wheel.as_uri(), "archive_info": {}}),
    )
    capabilities = SimpleNamespace(build_sha="a" * 40, target="x86_64-unknown-linux-musl", rule_digest="b" * 64)
    native = SimpleNamespace(path=runtime, sha256=digest(runtime)["sha256"])
    status = SimpleNamespace(
        available=True, compatible=True, reason="native_ready", identity=native, capabilities=capabilities
    )
    monkeypatch.setattr(
        module,
        "sys",
        SimpleNamespace(
            platform="linux",
            flags=SimpleNamespace(isolated=1),
            version_info=(3, 12, 14),
            executable=str(python),
            prefix=str(prefix),
        ),
    )
    monkeypatch.setattr(module, "platform", SimpleNamespace(machine=lambda: "x86_64", python_version=lambda: "3.12.14"))
    monkeypatch.setattr(
        module,
        "importlib",
        SimpleNamespace(
            metadata=SimpleNamespace(
                distribution=lambda _name: distribution_api,
                distributions=lambda: [SimpleNamespace(metadata={"Name": "tool"}, version="1.0")],
            )
        ),
    )
    replacements = {
        "codex_plugin_scanner.guard.config": SimpleNamespace(hook_fast_path_enabled=lambda: True),
        "codex_plugin_scanner.guard.native_runtime": SimpleNamespace(
            native_mode=lambda: "auto", native_runtime_status=lambda: note("native_status", status)
        ),
        "scripts.installed_canary_proof": SimpleNamespace(
            verify_installed_record=lambda _distribution: note("record", (state["record"], 4))
        ),
        "scripts.native_slo_artifact": SimpleNamespace(
            assert_installed_import_origin=lambda _distribution: note("import_origin"),
            installed_package_digest=lambda _distribution: state["package"],
            wheel_package_digest=lambda _wheel: "d" * 64,
        ),
        "scripts.native_slo_contract": SimpleNamespace(proof_environment_violations=lambda: state["environment"]),
    }
    for name, value in replacements.items():
        monkeypatch.setitem(sys.modules, name, value)
    expected = {
        "source_commit": "1" * 40,
        "source_tree": "2" * 40,
        "build_commit": "a" * 40,
        "build_tree": "2" * 40,
        "wheel_sha256": digest(wheel)["sha256"],
        "installed_manifest_sha256": "d" * 64,
        "runtime_sha256": native.sha256,
        "runtime_rule_digest": capabilities.rule_digest,
        "policy_fixture_sha256": "c" * 64,
        "corpus_sha256": rows[1]["sha256"],
        "producer_sha256": rows[0]["sha256"],
        "providers_sha256": module.json_digest(rows),
        "interpreter_sha256": digest(python)["sha256"],
        "package_version": "3.0.1",
        "python_version": "3.12.14",
        "default_native_features": True,
    }
    contract = {**expected, "providers": rows, "expected_identity": expected, "target": capabilities.target}
    subject = module.InstalledIdentity(wheel=wheel, python=python, providers=providers, contract=contract)
    return SimpleNamespace(
        subject=subject, expected=expected, state=state, observed=observed, status=status, capabilities=capabilities
    )


def test_complete_installed_identity_calls_original_guards_twice_and_preserves_rule_domain(installed_subject) -> None:
    item = installed_subject
    assert item.subject() == item.expected
    assert item.subject() == item.expected
    assert item.observed == ["import_origin", "record", "native_status"] * 2
    assert item.subject.inventories[0] == item.subject.inventories[1]
    assert item.subject.runtime == item.status.identity.path
    assert item.expected["runtime_rule_digest"] != item.expected["policy_fixture_sha256"]
    with pytest.raises(ValueError, match="identity_call_bound"):
        item.subject()


@pytest.mark.parametrize("stage", ["import_origin", "record", "native_status"])
def test_original_installed_guard_errors_are_not_ignored(installed_subject, stage: str) -> None:
    installed_subject.state["failure"] = stage
    with pytest.raises(RuntimeError, match=stage):
        installed_subject.subject()
    assert installed_subject.subject.inventories == []


@pytest.mark.parametrize(
    "kind",
    ["native_unavailable", "build", "target", "provider", "expected", "package", "mode", "default", "environment"],
)
def test_installed_identity_admission_refuses_concrete_mismatch(installed_subject, kind: str) -> None:
    item = installed_subject
    if kind == "native_unavailable":
        item.status.available = False
    elif kind == "build":
        item.capabilities.build_sha = "f" * 40
    elif kind == "target":
        item.capabilities.target = "x86_64-unknown-linux-gnu"
    elif kind == "provider":
        (item.subject.providers / item.subject.contract["providers"][0]["path"]).write_bytes(b"changed")
    elif kind == "expected":
        item.expected["runtime_rule_digest"] = "f" * 64
    elif kind == "package":
        item.state["package"] = "f" * 64
    elif kind == "mode":
        item.subject.python.chmod(0o777)
    elif kind == "default":
        item.subject.contract["default_native_features"] = False
    else:
        item.state["environment"] = ["forbidden_override"]
    with pytest.raises(ValueError):
        item.subject()


def test_local_installer_inventory_change_refuses_even_when_package_members_match(installed_subject) -> None:
    item = installed_subject
    assert item.subject() == item.expected
    item.state["record"] = "f" * 64
    with pytest.raises(ValueError, match="local_installation_changed"):
        item.subject()
