"""Closed diagnostic report fields; no payload values are admitted here."""

from __future__ import annotations

_PARENT_FACTS = {
    "error_kind",
    "launcher_latency_ms",
    "process_calls",
    "children",
    "registration_sha256",
    "original_allowed",
    "original_route",
}
_DAEMON_FACTS = {
    "error_kind",
    "projection_valid",
    "semantic_sha256",
    "entry_projection_sha256",
    "browser_fields_present",
    "exit_projection_valid",
    "exit_projection_sha256",
    "mutation_detected",
    "policy_admissions",
    "workspace_preparations",
    "worker_reviews",
    "native_edges",
    "encoded_envelopes",
    "native_exchanges",
    "decoded_edges",
    "receipt_submissions",
    "activity_submissions",
}
_REPORT_KEYS = {
    "schema",
    "side",
    "rows",
    "started",
    "completed",
    "in_flight",
    "capture_faults",
    "row_overflow",
    "stage_overflow",
    "restore_failures",
    "original_success",
    "tail_complete",
    "observation_complete",
    "qualification_eligible",
}
_DAEMON_KEYS = {
    "serve_returncode",
    "serve_error_kind",
    "session_attachments",
    "stop_observations",
    "final_stop",
    "final_stop_error_kind",
}


_EVENT_FIELDS = {
    "process_calls": {
        "semantic_sha256",
        "entry_projection_sha256",
        "browser_fields_present",
        "projection_valid",
        "input_bytes",
        "input_sha256",
        "exception",
        "returncode",
        "timed_out",
        "containment_failed",
        "output_limit_exceeded",
        "stdout_available",
        "stdout_bytes",
        "stdout_sha256",
        "stderr_available",
        "stderr_bytes",
        "stderr_sha256",
    },
    "children": {"pid"},
    "policy_admissions": {"exception", "returned_bool", "accepted"},
    "workspace_preparations": {"exception", "snapshot_returned"},
    "worker_reviews": {"entry_match", "exception", "returned_dict"},
    "native_edges": {"edge_returned", "edge_identity", "edge_authority_rust", "edge_decision", "exception"},
    "encoded_envelopes": {"envelope_available", "envelope_bytes", "envelope_sha256", "exception"},
    "native_exchanges": {
        "envelope_available",
        "envelope_bytes",
        "envelope_sha256",
        "reply_available",
        "reply_bytes",
        "reply_sha256",
        "exception",
        "returned_none",
    },
    "decoded_edges": {
        "edge_returned",
        "edge_identity",
        "edge_authority_rust",
        "edge_decision",
        "original_decoder_accepted",
        "exception",
    },
    "receipt_submissions": {"identity", "returned_bool", "accepted", "exception"},
    "activity_submissions": {"returned_bool", "accepted", "exception"},
}
_ERROR_KINDS = {
    None,
    "timeout",
    "os_error",
    "value_error",
    "type_error",
    "runtime_error",
    "interrupt",
    "system_exit",
    "other",
}
